spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: **?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: gkfdkqjwl1

  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블을 만들어줌 애플리케이션 실행시에 다 지우고 다시 실행
    properties:
      hibernate:
        show_sql: true
        format_sql: true
